---
- hosts: all
  become: yes
  tasks:
  - name: download artifacts
    get_url:
       url: http://18.234.106.129:8081/nexus/service/local/repositories/ram/content/ram/ram/1/ram-1.war
       dest: /usr/share/tomcat/webapps
       url_username: ram
       url_password: ram
      
  - name: restart tomcat
    systemd:
      name: tomcat
      state: restarted
