---
- name: install requied pakages
  yum:
    name: "{{ item }} "
  with_items:
  - java-1.8.0-openjdk
  - tomcat
  - tomcat-webapps
  - tomcat-admin-webapps

- name: copy user.xml
  template:
    src: tomcat-users.xml
    dest: /usr/share/tomcat/conf
    
- name: download artifacts
  get_url:
    url: http://18.234.106.129:8081/nexus/service/local/repositories/ram/content/ram/ram/1/ram-1.war
    dest: /usr/share/tomcat/webapps
    url_username: ram
    url_password: ram

- name: restart tomcat
  systemd:
    name: tomcat
    state: restarted
# tasks file for tomcat
